services:
  backend:
    build:
      context: ./ex1
      dockerfile: Dockerfile
    ports:
      - "16000:16000"
    depends_on:
      - mongodb
  frontend:
    build:
      context: ./ex2
      dockerfile: Dockerfile
    ports:
      - "16001:16001"
    depends_on:
      - backend
  mongodb:
    image: mongo:latest
    ports:
      - "27016:27016"
    depends_on:
      - mongo-seed
  mongo-seed:
    image: mongo:latest
    volumes:
      - ./contratos2024.json:/contratos2024.json
    command: mongoimport --host mongodb -d contratos -c contratos --type json --file contratos2024.json --jsonArray
